
export const BORDER_STATES = [
  'JAMMU AND KASHMIR', 'PUNJAB', 'RAJASTHAN', 'GUJARAT', 
  'WEST BENGAL', 'ASSAM', 'MEGHALAYA', 'TRIPURA', 
  'MIZORAM', 'MANIPUR', 'NAGALAND', 'ARUNACHAL PRADESH', 
  'SIKKIM', 'UTTARAKHAND', 'BIHAR', 'UTTAR PRADESH', 'LADAKH'
];

export const ALL_STATES = [
  'ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 
  'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU AND KASHMIR', 
  'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA PRADESH', 'MAHARASHTRA', 
  'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 
  'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 
  'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL', 'ANDAMAN AND NICOBAR ISLANDS', 
  'CHANDIGARH', 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'LAKSHADWEEP', 
  'DELHI', 'PUDUCHERRY', 'LADAKH'
];

export const MAJOR_URBAN_DISTRICTS = [
  'MUMBAI', 'DELHI', 'BENGALURU', 'HYDERABAD', 'AHMEDABAD', 
  'CHENNAI', 'KOLKATA', 'PUNE', 'SURAT', 'LUCKNOW', 'JAIPUR',
  'KANPUR', 'NAGPUR', 'INDORE', 'THANE', 'BHOPAL', 'VISAKHAPATNAM'
];

export const INDIA_GEOJSON_URL = 'https://raw.githubusercontent.com/india-in-data/india-states-2019/master/india_states.geojson';

export const RED_ZONE_PERCENTILE = 0.95;

export const normalizeStateName = (name: string): string => {
  if (!name) return "";
  let n = name.trim().toUpperCase()
    .replace(/\s+/g, ' ')
    .replace(/&/g, 'AND');

  const mapping: Record<string, string> = {
    "JAMMU & KASHMIR": "JAMMU AND KASHMIR",
    "TELANGANA": "TELANGANA",
    "UTTARANCHAL": "UTTARAKHAND",
    "ORISSA": "ODISHA",
    "PONDICHERRY": "PUDUCHERRY",
    "ANDAMAN & NICOBAR ISLANDS": "ANDAMAN AND NICOBAR ISLANDS",
    "A & N ISLANDS": "ANDAMAN AND NICOBAR ISLANDS",
    "D & N HAVELI AND DAMAN & DIU": "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "DADRA AND NAGAR HAVELI": "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "DAMAN AND DIU": "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU": "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "LAKSHADWEEP": "LAKSHADWEEP",
    "CHHATISGARH": "CHHATTISGARH",
    "ANDHRA PRADESH (BEFORE DIVISION)": "ANDHRA PRADESH"
  };

  return mapping[n] || n;
};
